### PR TITLE
chore(npm-package): update versions

### PR DESCRIPTION
**Pull request by micleners**
Ran `npm audit fix` to fix two out of four vulnerabilities. Updated package-lock.json as a result.

### CODE REVIEW

**Comment by travi** [comment]
two very minor things.

* since this is just a lockfile update, lets mark this commit as `chore` instead of `fix` since publishing a new version isn't needed in this case.
* since this is a change that is non-breaking and shouldn't even impact package behavior, lets open this PR against `master` rather than `beta`

**Comment by micleners** [comment]
Ok 👌 I wondered from your description earlier if it would fall under chore, but decided to be more prudent 
and go for fix. Fix would only be a PATCH semver version change, correct?

Sure, we can close here and I’ll reopen to master.

**Comment by travi** [comment]
> Fix would only be a PATCH semver version change, correct?

yep, thats correct. this change just doesnt impact anything that needs to be published.

> Sure, we can close here and I’ll reopen to master.

i think you should be able to just change the target in the drop down at the top of the PR page on your end. you'd still need to amend the commit message, though

**Comment by micleners** [comment]
I think I completed those two tasks

**Comment by micleners** [comment]
Now I'm even more certain of it

**Comment by travi** [comment]
thanks

**Pull request merged**
